### ISSUE TITLE
Letter styling missing from local.css

### ISSUE THREAD

**Issue by drgrigg** [jashua212/p-g-wodehouse_the-pothunters#2]
There's only one letter, in Chapter 10, but you've styled the salutation with a `<b>` tag, which would be taken care of if you'd included the usual letter styling from the manual (at section 7.7) and used a `<span>` instead. You don't need it all, just the following:

```
[epub|type~="z3998:sender"],
[epub|type~="z3998:salutation"],
[epub|type~="z3998:signature"]{
	font-variant: small-caps;
}
```

And you should add z3998:sender to the signature (manual 7.7.3.4).

**Comment by jashua212** [comment]
Change made.
