### ISSUE TITLE
Link in long description should be hyperlinked

### ISSUE THREAD

**Issue by drgrigg** [jashua212/p-g-wodehouse_the-pothunters#5]
I'll leave it to Alex to decide whether to include your link to the annotations website in the long description, but if you are to include it, it should be a concealed hyperlink, by which I mean:

```
Explanations for most of these references and phrases can be found in the annotations provided at Madame Eulalie’s Rare Plums website <a href="https://www.madameulalie.org/annots/pgwbooks/pgwtpot1.html">here</a>.
```
You would need to run se clean again to escape the html text in the above.

**Comment by jashua212** [comment]
Change made.
